"""
Image analysis tools using Groq's vision model.
Converted from image_analysis_agent.py to direct function tools.
"""

import os
import base64
from PIL import Image
import io
from typing import Dict
from pathlib import Path
from langchain_core.tools import tool
from groq import Groq

# Initialize Groq client
_groq_client = None

BACKEND_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = BACKEND_DIR.parent

def _get_groq_client():
    """Lazy initialization of Groq client."""
    global _groq_client
    if _groq_client is None:
        # Fetch the key here to ensure it catches vars set dynamically after import
        api_key = os.getenv("GROQ_API_KEY") 
        if not api_key:
            return None
        _groq_client = Groq(api_key=api_key)
    return _groq_client


def _resolve_image_path(image_path: str) -> str:
    """Resolve image path across common storage roots."""
    if not image_path:
        return image_path

    # Normalize slashes for cross-platform use
    normalized = image_path.replace("\\", "/")
    candidates = [Path(normalized)]

    # If path is relative, try backend and project root
    if not Path(normalized).is_absolute():
        candidates.append(BACKEND_DIR / normalized)
        candidates.append(PROJECT_ROOT / normalized)

    # If path starts with storage/, try from project root
    if normalized.startswith("storage/"):
        candidates.append(PROJECT_ROOT / normalized)

    for candidate in candidates:
        if candidate.exists():
            return str(candidate)

    return image_path


def _compress_and_encode_image(
    image_path: str, max_size_kb: int = 200, quality: int = 85
) -> str:
    """
    Read, compress, and encode image to base64.

    Args:
        image_path: Path to image file
        max_size_kb: Maximum size in KB
        quality: JPEG quality (1-100)

    Returns:
        Base64 encoded string
    """
    resolved_path = _resolve_image_path(image_path)
    if not os.path.exists(resolved_path):
        raise FileNotFoundError(f"Image not found: {resolved_path}")

    with open(resolved_path, "rb") as f:
        image = Image.open(f)

        # Convert to RGB if needed
        if image.mode in ("RGBA", "P"):
            image = image.convert("RGB")

        # Compress
        img_buffer = io.BytesIO()
        image.save(img_buffer, format="JPEG", quality=quality, optimize=True)

        # Reduce quality if too large
        while img_buffer.tell() / 1024 > max_size_kb and quality > 10:
            quality -= 10
            img_buffer = io.BytesIO()
            image.save(img_buffer, format="JPEG", quality=quality, optimize=True)

        return base64.b64encode(img_buffer.getvalue()).decode("utf-8")


@tool
def analyze_image(image_path: str = "", query: str = "") -> Dict:
    """
    Analyze an image using Groq's vision model and answer a question about it.

    Args:
        image_path: Local file path to the image (not a URL)
        query: Question to ask about the image

    Returns:
        Dictionary with answer to the query
    """
    try:
        client = _get_groq_client()

        if client is None:
            return {
                "error": "GROQ_API_KEY not configured - Image analysis requires GROQ_API_KEY environment variable"
            }

        if not image_path:
            return {"error": "No image_path provided"}

        if not query:
            query = "Describe the image in detail."

        # Compress and encode image
        compressed_base64 = _compress_and_encode_image(image_path)

        # Call Groq vision model
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": query},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{compressed_base64}",
                            },
                        },
                    ],
                }
            ],
            # Full model path required — Groq's API returns HTTP 404 if you use
            # the short alias "llama-4-scout". The complete ID includes the parameter
            # count and routing suffix that Groq uses for multi-tenant dispatch.
            model="meta-llama/llama-4-scout-17b-16e-instruct",
        )

        answer = chat_completion.choices[0].message.content
        if answer is None:
            answer = "No description generated by the model"

        return {"answer": answer, "query": query, "image_path": image_path}

    except FileNotFoundError as e:
        return {"error": str(e)}
    except Exception as e:
        return {"error": f"Image analysis failed: {str(e)}"}