"""
Image analysis tools using Groq's vision model.
Converted from image_analysis_agent.py to direct function tools.
"""

import os
import base64
from PIL import Image
import io
from typing import Dict
from langchain_core.tools import tool
from groq import Groq

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# Initialize Groq client
_groq_client = None

def _get_groq_client():
    """Lazy initialization of Groq client."""
    global _groq_client
    if _groq_client is None:
        if not GROQ_API_KEY:
            raise RuntimeError("GROQ_API_KEY not configured")
        _groq_client = Groq(api_key=GROQ_API_KEY)
    return _groq_client


def _compress_and_encode_image(image_path: str, max_size_kb: int = 200, quality: int = 85) -> str:
    """
    Read, compress, and encode image to base64.
    
    Args:
        image_path: Path to image file
        max_size_kb: Maximum size in KB
        quality: JPEG quality (1-100)
        
    Returns:
        Base64 encoded string
    """
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Image not found: {image_path}")
    
    with open(image_path, "rb") as f:
        image = Image.open(f)
        
        # Convert to RGB if needed
        if image.mode in ("RGBA", "P"):
            image = image.convert("RGB")
        
        # Compress
        img_buffer = io.BytesIO()
        image.save(img_buffer, format="JPEG", quality=quality, optimize=True)
        
        # Reduce quality if too large
        while img_buffer.tell() / 1024 > max_size_kb and quality > 10:
            quality -= 10
            img_buffer = io.BytesIO()
            image.save(img_buffer, format="JPEG", quality=quality, optimize=True)
        
        return base64.b64encode(img_buffer.getvalue()).decode('utf-8')


@tool
def analyze_image(image_path: str, query: str) -> Dict:
    """
    Analyze an image using Groq's vision model and answer a question about it.
    
    Args:
        image_path: Local file path to the image
        query: Question to ask about the image
        
    Returns:
        Dictionary with answer to the query
    """
    try:
        client = _get_groq_client()
        
        # Compress and encode image
        compressed_base64 = _compress_and_encode_image(image_path)
        
        # Call Groq vision model
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": query},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{compressed_base64}",
                            },
                        },
                    ],
                }
            ],
            model="meta-llama/llama-4-scout-17b-16e-instruct",
        )
        
        answer = chat_completion.choices[0].message.content
        if answer is None:
            answer = "No description generated by the model"
        
        return {
            "answer": answer,
            "query": query,
            "image_path": image_path
        }
        
    except FileNotFoundError as e:
        return {"error": str(e)}
    except Exception as e:
        return {"error": f"Image analysis failed: {str(e)}"}
