"""add_artifact_embeddings_table

Revision ID: 48cf81f098d2
Revises: ec808ac09b10
Create Date: 2026-02-28 17:07:40.051211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '48cf81f098d2'
down_revision: Union[str, Sequence[str], None] = 'ec808ac09b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source_objective', sa.Text(), nullable=True),
    sa.Column('source_agent', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_embeddings_artifact_id'), 'artifact_embeddings', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_artifact_embeddings_artifact_type'), 'artifact_embeddings', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifact_embeddings_id'), 'artifact_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_artifact_embeddings_user_id'), 'artifact_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_embeddings_user_id'), table_name='artifact_embeddings')
    op.drop_index(op.f('ix_artifact_embeddings_id'), table_name='artifact_embeddings')
    op.drop_index(op.f('ix_artifact_embeddings_artifact_type'), table_name='artifact_embeddings')
    op.drop_index(op.f('ix_artifact_embeddings_artifact_id'), table_name='artifact_embeddings')
    op.drop_table('artifact_embeddings')
    # ### end Alembic commands ###
