"""initial_schema

Revision ID: 888609832433
Revises: 
Create Date: 2025-11-24 23:20:19.032374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888609832433'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_agent_credentials_agent_id'), table_name='agent_credentials')
    op.drop_index(op.f('idx_agent_credentials_user_id'), table_name='agent_credentials')
    op.create_index(op.f('ix_agent_credentials_user_id'), 'agent_credentials', ['user_id'], unique=False)
    op.drop_constraint(op.f('agent_credentials_agent_id_fkey'), 'agent_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'agent_credentials', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_credentials', type_='foreignkey')
    op.create_foreign_key(op.f('agent_credentials_agent_id_fkey'), 'agent_credentials', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_credentials_user_id'), table_name='agent_credentials')
    op.create_index(op.f('idx_agent_credentials_user_id'), 'agent_credentials', ['user_id'], unique=False)
    op.create_index(op.f('idx_agent_credentials_agent_id'), 'agent_credentials', ['agent_id'], unique=False)
    # ### end Alembic commands ###
