"""Remove rating system columns

Revision ID: e7a71c4bf948
Revises: initial_complete_schema
Create Date: 2026-02-10 23:04:03.525584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'e7a71c4bf948'
down_revision: Union[str, Sequence[str], None] = 'initial_complete_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('tag_color', sa.String(length=7), nullable=True),
    sa.Column('tag_description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_tags_tag_id'), 'conversation_tags', ['tag_id'], unique=True)
    op.create_index(op.f('ix_conversation_tags_user_id'), 'conversation_tags', ['user_id'], unique=False)
    op.create_table('agent_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('capability_text', sa.String(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_capabilities_id'), 'agent_capabilities', ['id'], unique=False)
    op.create_table('agent_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('encrypted_credentials', sa.JSON(), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('auth_header_name', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_credentials_user_id'), 'agent_credentials', ['user_id'], unique=False)
    op.create_table('conversation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=True),
    sa.Column('task_agent_pairs', sa.JSON(), nullable=False),
    sa.Column('task_plan', sa.JSON(), nullable=False),
    sa.Column('plan_graph', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['user_threads.thread_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_plans_plan_id'), 'conversation_plans', ['plan_id'], unique=True)
    op.create_index(op.f('ix_conversation_plans_thread_id'), 'conversation_plans', ['thread_id'], unique=False)
    op.create_index(op.f('ix_conversation_plans_user_id'), 'conversation_plans', ['user_id'], unique=False)
    op.create_table('conversation_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_role', sa.String(length=50), nullable=True),
    sa.Column('message_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['user_threads.thread_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_search_thread_id'), 'conversation_search', ['thread_id'], unique=False)
    op.create_index(op.f('ix_conversation_search_user_id'), 'conversation_search', ['user_id'], unique=False)
    op.create_table('conversation_tag_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('tag_id', sa.String(length=255), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['conversation_tags.tag_id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['user_threads.thread_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_tag_assignments_tag_id'), 'conversation_tag_assignments', ['tag_id'], unique=False)
    op.create_index(op.f('ix_conversation_tag_assignments_thread_id'), 'conversation_tag_assignments', ['thread_id'], unique=False)
    op.create_table('workflow_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('webhook_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_webhooks_id'), 'workflow_webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_webhooks_user_id'), 'workflow_webhooks', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_webhooks_webhook_id'), 'workflow_webhooks', ['webhook_id'], unique=True)
    op.drop_index(op.f('ix_user_connections_app_slug'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_connection_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_user_id'), table_name='user_connections')
    op.drop_table('user_connections')
    op.drop_index(op.f('ix_connection_logs_app_slug'), table_name='connection_logs')
    op.drop_index(op.f('ix_connection_logs_connection_id'), table_name='connection_logs')
    op.drop_index(op.f('ix_connection_logs_created_at'), table_name='connection_logs')
    op.drop_index(op.f('ix_connection_logs_id'), table_name='connection_logs')
    op.drop_index(op.f('ix_connection_logs_user_id'), table_name='connection_logs')
    op.drop_table('connection_logs')
    op.drop_column('agent_usage_analytics', 'metrics')
    op.alter_column('agents', 'capabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('agents', 'rating')
    op.drop_column('agents', 'image_url')
    op.drop_column('agents', 'rating_count')
    op.drop_column('conversation_analytics', 'metrics')
    op.drop_column('workflow_execution_analytics', 'metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_execution_analytics', sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('conversation_analytics', sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('agents', 'capabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('agent_usage_analytics', sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('connection_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('app_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('connection_logs_pkey'))
    )
    op.create_index(op.f('ix_connection_logs_user_id'), 'connection_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_connection_logs_id'), 'connection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_connection_logs_created_at'), 'connection_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_connection_logs_connection_id'), 'connection_logs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_connection_logs_app_slug'), 'connection_logs', ['app_slug'], unique=False)
    op.create_table('user_connections',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('app_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('connected_account_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('auth_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_verified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('app_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_connections_pkey'))
    )
    op.create_index(op.f('ix_user_connections_user_id'), 'user_connections', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_connections_id'), 'user_connections', ['id'], unique=False)
    op.create_index(op.f('ix_user_connections_connection_id'), 'user_connections', ['connection_id'], unique=True)
    op.create_index(op.f('ix_user_connections_app_slug'), 'user_connections', ['app_slug'], unique=False)
    op.drop_index(op.f('ix_workflow_webhooks_webhook_id'), table_name='workflow_webhooks')
    op.drop_index(op.f('ix_workflow_webhooks_user_id'), table_name='workflow_webhooks')
    op.drop_index(op.f('ix_workflow_webhooks_id'), table_name='workflow_webhooks')
    op.drop_table('workflow_webhooks')
    op.drop_index(op.f('ix_conversation_tag_assignments_thread_id'), table_name='conversation_tag_assignments')
    op.drop_index(op.f('ix_conversation_tag_assignments_tag_id'), table_name='conversation_tag_assignments')
    op.drop_table('conversation_tag_assignments')
    op.drop_index(op.f('ix_conversation_search_user_id'), table_name='conversation_search')
    op.drop_index(op.f('ix_conversation_search_thread_id'), table_name='conversation_search')
    op.drop_table('conversation_search')
    op.drop_index(op.f('ix_conversation_plans_user_id'), table_name='conversation_plans')
    op.drop_index(op.f('ix_conversation_plans_thread_id'), table_name='conversation_plans')
    op.drop_index(op.f('ix_conversation_plans_plan_id'), table_name='conversation_plans')
    op.drop_table('conversation_plans')
    op.drop_index(op.f('ix_agent_credentials_user_id'), table_name='agent_credentials')
    op.drop_table('agent_credentials')
    op.drop_index(op.f('ix_agent_capabilities_id'), table_name='agent_capabilities')
    op.drop_table('agent_capabilities')
    op.drop_index(op.f('ix_conversation_tags_user_id'), table_name='conversation_tags')
    op.drop_index(op.f('ix_conversation_tags_tag_id'), table_name='conversation_tags')
    op.drop_table('conversation_tags')
    # ### end Alembic commands ###
