"""Add telemetry execution tracking

Revision ID: ec808ac09b10
Revises: 42363728b514
Create Date: 2026-02-28 15:31:30.854924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec808ac09b10'
down_revision: Union[str, Sequence[str], None] = '42363728b514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_records_agent_name'), 'agent_execution_records', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_execution_records_id'), 'agent_execution_records', ['id'], unique=False)
    op.create_index(op.f('ix_agent_execution_records_thread_id'), 'agent_execution_records', ['thread_id'], unique=False)
    op.create_index(op.f('ix_agent_execution_records_timestamp'), 'agent_execution_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_execution_records_user_id'), 'agent_execution_records', ['user_id'], unique=False)
    op.create_table('llm_telemetry_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_telemetry_records_agent_name'), 'llm_telemetry_records', ['agent_name'], unique=False)
    op.create_index(op.f('ix_llm_telemetry_records_id'), 'llm_telemetry_records', ['id'], unique=False)
    op.create_index(op.f('ix_llm_telemetry_records_thread_id'), 'llm_telemetry_records', ['thread_id'], unique=False)
    op.create_index(op.f('ix_llm_telemetry_records_timestamp'), 'llm_telemetry_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_llm_telemetry_records_user_id'), 'llm_telemetry_records', ['user_id'], unique=False)
    op.create_table('tool_execution_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_execution_records_id'), 'tool_execution_records', ['id'], unique=False)
    op.create_index(op.f('ix_tool_execution_records_thread_id'), 'tool_execution_records', ['thread_id'], unique=False)
    op.create_index(op.f('ix_tool_execution_records_timestamp'), 'tool_execution_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tool_execution_records_tool_name'), 'tool_execution_records', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_execution_records_user_id'), 'tool_execution_records', ['user_id'], unique=False)
    op.drop_index(op.f('idx_agent_credentials_agent_id'), table_name='agent_credentials')
    op.drop_index(op.f('idx_agent_credentials_user_id'), table_name='agent_credentials')
    op.create_index(op.f('ix_agent_credentials_user_id'), 'agent_credentials', ['user_id'], unique=False)
    op.drop_constraint(op.f('agent_credentials_agent_id_fkey'), 'agent_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'agent_credentials', 'agents', ['agent_id'], ['id'])
    op.add_column('workflows', sa.Column('plan_graph', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'plan_graph')
    op.drop_constraint(None, 'agent_credentials', type_='foreignkey')
    op.create_foreign_key(op.f('agent_credentials_agent_id_fkey'), 'agent_credentials', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_credentials_user_id'), table_name='agent_credentials')
    op.create_index(op.f('idx_agent_credentials_user_id'), 'agent_credentials', ['user_id'], unique=False)
    op.create_index(op.f('idx_agent_credentials_agent_id'), 'agent_credentials', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_tool_execution_records_user_id'), table_name='tool_execution_records')
    op.drop_index(op.f('ix_tool_execution_records_tool_name'), table_name='tool_execution_records')
    op.drop_index(op.f('ix_tool_execution_records_timestamp'), table_name='tool_execution_records')
    op.drop_index(op.f('ix_tool_execution_records_thread_id'), table_name='tool_execution_records')
    op.drop_index(op.f('ix_tool_execution_records_id'), table_name='tool_execution_records')
    op.drop_table('tool_execution_records')
    op.drop_index(op.f('ix_llm_telemetry_records_user_id'), table_name='llm_telemetry_records')
    op.drop_index(op.f('ix_llm_telemetry_records_timestamp'), table_name='llm_telemetry_records')
    op.drop_index(op.f('ix_llm_telemetry_records_thread_id'), table_name='llm_telemetry_records')
    op.drop_index(op.f('ix_llm_telemetry_records_id'), table_name='llm_telemetry_records')
    op.drop_index(op.f('ix_llm_telemetry_records_agent_name'), table_name='llm_telemetry_records')
    op.drop_table('llm_telemetry_records')
    op.drop_index(op.f('ix_agent_execution_records_user_id'), table_name='agent_execution_records')
    op.drop_index(op.f('ix_agent_execution_records_timestamp'), table_name='agent_execution_records')
    op.drop_index(op.f('ix_agent_execution_records_thread_id'), table_name='agent_execution_records')
    op.drop_index(op.f('ix_agent_execution_records_id'), table_name='agent_execution_records')
    op.drop_index(op.f('ix_agent_execution_records_agent_name'), table_name='agent_execution_records')
    op.drop_table('agent_execution_records')
    # ### end Alembic commands ###
